import {
  ElAlert,
  // ElAffix,
  // ElAside,
  // ElAutocomplete,
  // ElAvatar,
  // ElBacktop,
  // ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  // ElCalendar,
  // ElCard,
  // ElCarousel,
  // ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  // ElCollapse,
  // ElCollapseItem,
  ElCollapseTransition,
  ElColorPicker,
  // ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  // ElFooter,
  ElForm,
  ElFormItem,
  // ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  // ElInputNumber,
  ElLink,
  // ElMain,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElOption,
  ElOptionGroup,
  // ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  // ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRate,
  ElResult,
  ElEmpty,
  ElRow,
  ElScrollbar,
  ElSelect,
  // ElSlider,
  ElSkeleton,
  ElSkeletonItem,
  ElStep,
  ElSteps,
  ElSubMenu,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTag,
  ElTimePicker,
  // ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  // ElTransfer,
  ElTree,
  ElUpload,
  ElConfigProvider,
  // ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox
  // ElNotification
} from 'element-plus';

const components = [
  ElAlert,
  // ElAffix,
  // ElAside,
  // ElAutocomplete,
  // ElAvatar,
  // ElBacktop,
  // ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  // ElCalendar,
  // ElCard,
  // ElCarousel,
  // ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  // ElCollapse,
  // ElCollapseItem,
  ElCollapseTransition,
  ElColorPicker,
  // ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  // ElFooter,
  ElForm,
  ElFormItem,
  // ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  // ElInputNumber,
  ElLink,
  // ElMain,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElOption,
  ElOptionGroup,
  // ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  // ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  // ElRate,
  ElResult,
  ElEmpty,
  ElRow,
  ElScrollbar,
  ElSelect,
  // ElSlider,
  ElSkeleton,
  ElSkeletonItem,
  ElStep,
  ElSteps,
  ElSubMenu,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTag,
  ElTimePicker,
  // ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  // ElTransfer,
  ElTree,
  ElUpload,
  ElConfigProvider
];

// 样式并未按需加载 一次性引入
import 'element-plus/theme-chalk/index.css';

// 引入自定义组件(支持按需)
import FeComponents from '@fe/vue-component-library';
// css文件须一次性引入
import '@fe/vue-component-library/lib/style/index.css';
// 引入自定义主题变量(其中有覆盖element-plus定义的变量)
import '@/assets/css/theme.css';

const plugins = [ElLoading, ElMessage, ElMessageBox];

export default function useComponents(app: any) {
  // 注册element-plus组件
  components.forEach(component => app.component(component.name, component));
  plugins.forEach(plugin => app.use(plugin));

  // 注册自定义组件
  app.use(FeComponents);
}
